"""create video verification table

Revision ID: 45546bd2202d
Revises: 0f7972211206
Create Date: 2026-08-01 20:19:13.292630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45546bd2202d'
down_revision: Union[str, Sequence[str], None] = '0f7972211206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_schedule_id', sa.Integer(), nullable=False),
    sa.Column('verification_date', sa.Date(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_schedule_id'], ['medicine_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_verifications')
    # ### end Alembic commands ###
