"""create control schedule table

Revision ID: 50f310b266ab
Revises: 00ef820c46a4
Create Date: 2026-08-06 20:45:11.576769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f310b266ab'
down_revision: Union[str, Sequence[str], None] = '00ef820c46a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_id', sa.Integer(), nullable=False),
    sa.Column('control_date', sa.Date(), nullable=False),
    sa.Column('control_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'MISSED', 'CANCELLED', name='controlschedulestatus'), nullable=False),
    sa.Column('doctor_note', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_schedules')
    # ### end Alembic commands ###
