"""make user facility required

Revision ID: 5e3fe3201044
Revises: 6b4776cefe33
Create Date: 2026-08-18 20:22:03.171705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5e3fe3201044"
down_revision: Union[str, Sequence[str], None] = "6b4776cefe33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # Assign existing users to the first active facility
    op.execute("""
        UPDATE users
        SET facility_id = (
            SELECT id
            FROM health_facilities
            WHERE is_active = TRUE
            ORDER BY id
            LIMIT 1
        )
        WHERE facility_id IS NULL
    """)

    # Make facility_id required
    op.alter_column(
        "users",
        "facility_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "facility_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
