"""allow nullable facility for admin

Revision ID: 6e541d04a025
Revises: 5e3fe3201044
Create Date: 2026-08-18 22:08:14.454108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e541d04a025'
down_revision: Union[str, Sequence[str], None] = '5e3fe3201044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'facility_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'facility_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
