"""create treatment table

Revision ID: 842ae79e9149
Revises: 54763fdece1a
Create Date: 2026-07-30 17:26:24.980186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842ae79e9149'
down_revision: Union[str, Sequence[str], None] = '54763fdece1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=False),
    sa.Column('therapy_start_date', sa.Date(), nullable=False),
    sa.Column('therapy_end_date', sa.Date(), nullable=False),
    sa.Column('phase', sa.Enum('INTENSIVE', 'CONTINUATION', name='treatmentphase'), nullable=False),
    sa.Column('regimen', sa.Enum('CATEGORY_1', 'CATEGORY_2', 'MDR', name='regimenenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DROPPED', name='treatmentstatus'), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('doctor_note', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatments')
    # ### end Alembic commands ###
