"""add is_active to face verifications

Revision ID: ac21ac10f42f
Revises: 622ee0d9e156
Create Date: 2026-09-06 01:31:33.004543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac21ac10f42f'
down_revision: Union[str, Sequence[str], None] = '622ee0d9e156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_verifications', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_verifications', 'is_active')
    # ### end Alembic commands ###
