"""add file metadata to video verification

Revision ID: cf8be3fff586
Revises: 45546bd2202d
Create Date: 2026-08-01 20:42:59.498452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8be3fff586'
down_revision: Union[str, Sequence[str], None] = '45546bd2202d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_verifications', sa.Column('video_path', sa.String(length=255), nullable=False))
    op.add_column('video_verifications', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('video_verifications', sa.Column('mime_type', sa.String(length=50), nullable=False))
    op.add_column('video_verifications', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('video_verifications', sa.Column('thumbnail_path', sa.String(length=255), nullable=True))
    op.drop_column('video_verifications', 'thumbnail_url')
    op.drop_column('video_verifications', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_verifications', sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('video_verifications', sa.Column('thumbnail_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('video_verifications', 'thumbnail_path')
    op.drop_column('video_verifications', 'file_size')
    op.drop_column('video_verifications', 'mime_type')
    op.drop_column('video_verifications', 'file_name')
    op.drop_column('video_verifications', 'video_path')
    # ### end Alembic commands ###
